# Generated by Django 3.2.4 on 2022-09-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Task status'),
        ),
    ]
